name: Build and Deploy Custom Image

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application Artifact
        run: |
          zip -r app.zip . -x ".git/*" -x ".github/*"
        env:
          NODE_ENV: production  # Set environment variable for build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.zip
          path: app.zip

  packer_build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Application Artifact
        uses: actions/download-artifact@v3
        with:
          name: app.zip

      - name: Set up Packer
        uses: hashicorp/packer-github-actions@v1.0.4

      - name: Run Packer
        run: |
          ls
          pwd
          cd packer_folder
          packer init packertemp.pkr.hcl

          packer build -var "aws_access_key=${{ secrets.ACCESS_KEY }}" \
             -var "aws_secret_access_key=${{ secrets.SECRET_ACCESS_KEY }}" \
             packertemp.pkr.hcl

      - name: Build Custom Image with Packer
        run: |
          packer init .
          packer build .
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
