name: Build and Deploy Custom Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository to get the webapp and packer fold
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the application artifact (zip)
      - name: Build Application Artifact
        run: |
          zip -r app.zip . -x ".git/*" -x ".github/*"  # Creates the artifact
          ls -al
        env:
          NODE_ENV: production

      # Step 3: Upload the artifact to GitHub Actions
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app.zip  # This artifact will be passed to the Packer build
          path: app.zip

      # Step 2: Download the built application artifact
      - name: Download Application Artifact
        uses: actions/download-artifact@v3
        with:
          name: app.zip

      # Step 3: Move the artifact to the packer folder
      - name: Move Artifact to Packer Folder
        run: |
          ls -al
          mv app.zip ./packer/  # Move the zipped artifact to the correct folder

      # Step 4: Set up Packer
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
         version: 1.11.2

      # Step 5: Run Packer to build the custom image
      - name: Run Packer
        working-directory: ./packer  # Ensure we are in the correct directory where the Packer files are
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          packer init aws.pkr.hcl  # Initialize Packer with the configuration
          packer build aws.pkr.hcl
