name: Continuous Integration workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_DIALECT: mysql
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Set up MySQL
      run: |
        sudo apt update
        sudo apt install -y mysql-server
        sudo systemctl start mysql
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
        sudo mysql -e "CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ secrets.DB_USER }}'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"
 
    - name: Install npm dependencies
      run: npm install
 
    - name: Install express dependencies
      run: npm install express
 
    - name: Install bcrypt and Sequelize dependencies
      run: |
        npm install bcrypt
        npm install sequelize mysql2
        npm install sequelize-cli --save-dev
 
    - name: Set up MySQL database with Sequelize
      run: |
        npx sequelize-cli db:create
    
    - name: Install Jest dependencies
      run: npm install --save-dev jest
 
    - name: Run Jest tests
      run: npm test
