name: Continuous Integration workflow

on:
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
  
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}                              
          MYSQL_USER: ${{ secrets.DB_USER_TEST }}                                    
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: Install dependencies
        run: npm install
  
      - name: Check for SQL to be healthy
        run: |
          for i in `seq 1 30`; do
            if echo "SELECT 1" | mysql -h 127.0.0.1 -u${{ secrets.DB_USER_TEST }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} ; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 15
          done
  
          
      - name: Running my tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 3306
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER_TEST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: npm test

        # Packer-related steps
      - name: Set up Packer
        uses: hashicorp/setup-packer@latest

      - name: Run Packer fmt check on aws.pkr.hcl
        working-directory: ./packer
        run: |
          packer fmt -check aws.pkr.hcl
        
        continue-on-error: false  

      - name: Validate Packer template aws.pkr.hcl
        working-directory: ./packer
        run: |
          packer validate aws.pkr.hcl
        # If validation fails, the workflow will fail
        continue-on-error: false


