name: Continuous Integration workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USER: myuser  # Storing the username here for clarity

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up MySQL
        run: |
          sudo apt update
          sudo apt install -y mysql-server
          sudo systemctl start mysql
          # Set root password and avoid errors with root access
          sudo mysqladmin -u root password '${{ secrets.DB_PASSWORD }}'
          # Log in using root with password and create the new user
          sudo mysql -u root -p${{ secrets.DB_PASSWORD }} -e "CREATE USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${{ secrets.DB_PASSWORD }}';"
          sudo mysql -u root -p${{ secrets.DB_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB_NAME }}.* TO '${{ env.DB_USER }}'@'localhost';"
          sudo mysql -u root -p${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"
        
      - name: Set up Node.js using GitHub Action
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
    
      - name: Install npm dependencies
        run: npm ci
    
      - name: Run Sequelize migrations
        run: npx sequelize-cli db:migrate --url "mysql://${{ env.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost/${{ secrets.DB_NAME }}"
    
      - name: Run tests
        run: npm test -- --exit
