name: Continuous Integration workflow

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Packer-related steps
      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.11.2

      - name: Run Packer fmt check on aws.pkr.hcl
        working-directory: ./packer
        run: |
          packer fmt -check aws.pkr.hcl
        continue-on-error: false

      - name: Validate Packer template aws.pkr.hcl
        working-directory: ./packer
        run: |
          packer validate -syntax-only aws.pkr.hcl
        continue-on-error: false
